# Create Medicine
POST http://localhost:3333/medicines HTTP/1.1
content-type: application/json

{
  "name": "Brufen",
  "reference": "BR400",
  "active_ingredient": "Chocolate",
  "brand": "Adidas",
  "intake": "mouth"
}
