# Create User
POST http://localhost:3333/medicines HTTP/1.1
content-type: application/json

{
  "name": "Ben U Ron",
  "reference": "BE762",
  "active_ingredient": "Orange",
  "brand": "Nike",
  "intake": "Put on the ass"
}
