# Create User
POST http://localhost:3333/tests HTTP/1.1
content-type: application/json

{
  "user": {
    "nif": 242078265,
    "name": "João Gomes",
    "email": "joao@gmail.com",
    "phone": 911776543
  },
  "result": true
}