# Create Test
POST http://localhost:3333/tests HTTP/1.1
content-type: application/json

{
  "user": {
    "nif": 908765432,
    "name": "Dara Alves",
    "email": "da@gmail.com",
    "phone": 987654321
  },
  "result": false
}